import assert from 'node:assert/strict';
import fs from 'node:fs';
import { randomUUID } from 'node:crypto';
const base='http://127.0.0.1:5173';
const unauth=await fetch(base+'/api/progress'); assert.equal(unauth.status,401);
const account=await fetch(base+'/account'); assert.equal(account.status,200); assert((await account.text()).includes('使用 ChatGPT 账号登录'));
const home=await fetch(base+'/study.html'); assert.equal(home.status,200);assert((await home.text()).includes('id="accountEntry"'));
const signin=await fetch(base+'/signin-with-chatgpt?return_to=/study.html',{redirect:'manual'}); assert.equal(signin.status,302); assert.equal(signin.headers.get('location'),'/study.html');
const cookie=signin.headers.get('set-cookie').split(';')[0];assert(cookie.startsWith('__sites_local_auth='));
const before=await fetch(base+'/api/progress',{headers:{cookie}}); assert.equal(before.status,200); const initial=await before.json();
const q=JSON.parse(fs.readFileSync('src/learning.json','utf8')).questions[0];
const count=initial.state.attempts[q.id]?.count||0;
const body={type:'answer',questionId:q.id,choice:(q.answer+1)%4,mutationId:randomUUID()};
const options={method:'POST',headers:{cookie,Origin:base,'Content-Type':'application/json'},body:JSON.stringify(body)};
const answer=await fetch(base+'/api/progress',options);assert.equal(answer.status,200);const saved=await answer.json();assert.equal(saved.correct,false);assert.equal(saved.state.attempts[q.id].count,count+1);
const retry=await fetch(base+'/api/progress',options);assert.equal(retry.status,200);assert.equal((await retry.json()).state.attempts[q.id].count,count+1);
const reload=await fetch(base+'/api/progress',{headers:{cookie}});assert.equal((await reload.json()).state.attempts[q.id].count,count+1);
const loggedAccount=await fetch(base+'/account',{headers:{cookie}});const text=await loggedAccount.text();assert(text.includes('退出登录'));assert(text.includes('Seedy'));
const signout=await fetch(base+'/signout-with-chatgpt?return_to=/account',{headers:{cookie},redirect:'manual'});assert.equal(signout.status,302);assert(signout.headers.get('set-cookie').includes('Max-Age=0'));
assert.equal((await fetch(base+'/api/progress')).status,401);
console.log('Passed against local Worker and real D1: login page, anonymous denial, sign-in, wrong-answer persistence, reload, idempotent retry and sign-out.');
